### ISSUE TITLE
[False Positive] <Move check> Scaffolding Bug

### ISSUE THREAD

**Issue by crafter23456** [QuantumSuite/MatrixChecks#6]
### Before you report:

[ ] This issue does not happen on the default Matrix config files.  
[x] I am on the latest version of Matrix and MatrixChecks.  
[x] I can reproduce this issue and have the steps to do so.

### Steps to reproduce

https://drive.google.com/file/d/10BYnaFs-riT5haaWVE-S3Q2DWiW9d3Y_/view?usp=sharing
Scaffolding bug
if I jump in gamemode 1 its normaly, but in gm 0 it is very buggy you can see in that video. I tested it without Matrix and it was normal.

### Information
- **Client Version:**  1.16.5
- **Server Version:**  Paper 1.16.5

**Comment by encode42** [comment]
This is an issue with the anticheat itself; there's nothing I do besides disabling the check. Report this on [their issue tracker](https://github.com/jiangdashao/Matrix-Issues).
